version: '3'

services:
  # MariaDB
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdasdasd
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mariadb_scripts:/docker-entrypoint-initdb.d

  # Add Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  # Django application
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - elasticsearch

# Define the esdata volume
volumes:
  esdata:

