version: '3'

services:
  apicore:
    build: ./apicore
    volumes:
      - .:/var/www
    ports:
      - "8001:8001"

  api-mongo-test:
    build: ./api-mongo-test
    volumes:
      - .:/var/www
    ports:
      - "8002:8002"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdasdasd
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mariadb_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    volumes:
      - /sessions
    restart: always
    ports:
      - "8088:80"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
