# Generated by Django 3.2.10 on 2023-03-23 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+', message='Invalid characters')])),
                ('lname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+', message='Invalid characters')])),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+', message='Invalid characters')])),
                ('dob', models.DateField(validators=[django.core.validators.RegexValidator('^[0-9-]+', message='Invalid characters')])),
                ('status', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_form',
            },
        ),
    ]
