# Generated by Django 3.2.10 on 2023-03-23 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUCountries',
            fields=[
                ('id', models.SmallAutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('country', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+', message='Invalid characters')])),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+', message='Invalid characters')])),
                ('calling_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9+]+', message='Invalid characters')])),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'countries_master',
            },
        ),
    ]
