# Generated by Django 3.2.10 on 2023-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_eucountries'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
