# Generated by Django 3.2.10 on 2023-03-24 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_myform_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.-_]+', message='Invalid characters')]),
        ),
    ]
