# Generated by Django 3.2.10 on 2023-03-26 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_myform_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuMaster',
            fields=[
                ('id', models.SmallAutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('menu_icon', models.CharField(default='list', max_length=10, validators=[django.core.validators.RegexValidator('^[a-z-]+', message='Invalid characters')])),
                ('menu_route', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-Z\\s]+', message='Invalid characters')])),
                ('status', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_menu_master',
            },
        ),
    ]
