# Generated by Django 3.2.10 on 2023-03-26 14:21

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_adminmenumaster_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmenumaster',
            name='menu_icon',
            field=models.CharField(default=backend.models.default_list, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-z-]+')]),
        ),
        migrations.AlterField(
            model_name='adminmenumaster',
            name='menu_name',
            field=models.CharField(default=backend.models.default_undefined, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
        migrations.AlterField(
            model_name='adminmenumaster',
            name='menu_route',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
        migrations.AlterField(
            model_name='eucountries',
            name='calling_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[0-9+]+')]),
        ),
        migrations.AlterField(
            model_name='eucountries',
            name='country',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
        migrations.AlterField(
            model_name='eucountries',
            name='country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='myform',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9.-_]+')]),
        ),
        migrations.AlterField(
            model_name='myform',
            name='dob',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[0-9-]+')]),
        ),
        migrations.AlterField(
            model_name='myform',
            name='fname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
        migrations.AlterField(
            model_name='myform',
            name='gender',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='myform',
            name='lname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
    ]
