# Generated by Django 3.2.10 on 2023-03-26 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20230326_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmenumaster',
            name='menu_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z\\s]+')]),
        ),
    ]
