# Generated by Django 3.2.10 on 2023-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_adminmenumaster_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmenumaster',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
