# Generated by Django 3.2.10 on 2023-03-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_adminmenumaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'This email already exists'}, max_length=50, unique=True),
        ),
    ]
