# Generated by Django 3.2.10 on 2023-03-27 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_myform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmenumaster',
            name='menu_order',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[0-9]+')]),
        ),
    ]
